BASEURL ?= http://web.data.dsdbi.links.com.au/data/dataset/56741bd1-3cc3-4f48-9f3d-51bda9954ca5/resource/75f1286a-6326-4688-80b1-83ca91f20427/download/.filesdata.vicprincipalbicyclenetwork.kmz

PBN_GDA94.kml:
	unzip network.kmz

network.kmz:
	wget ${BASEURL} -O network.kmz
